"""add billing fields to tenant

Revision ID: 09629af3068e
Revises: e8279d3cd8ac
Create Date: 2026-03-17 21:42:31.346627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09629af3068e'
down_revision = 'e8279d3cd8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
