"""add paths_found messages_drafted to tenant

Revision ID: 430eb7832091
Revises: 63b622824537
Create Date: 2026-03-17 20:56:57.141290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430eb7832091'
down_revision = '63b622824537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paths_found', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('messages_drafted', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('messages_drafted')
        batch_op.drop_column('paths_found')

    # ### end Alembic commands ###
