"""add relationship_note to edges

Revision ID: 63b622824537
Revises: c50eae065823
Create Date: 2026-03-17 17:03:32.312591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b622824537'
down_revision = 'c50eae065823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_column('relationship_note')

    # ### end Alembic commands ###
