"""create people and edges

Revision ID: 77043cb74d96
Revises: 
Create Date: 2026-02-24 22:35:04.135277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77043cb74d96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_person_id', sa.Integer(), nullable=False),
    sa.Column('to_person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_person_id', 'to_person_id', name='uq_edge_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    op.drop_table('people')
    # ### end Alembic commands ###
