"""add title company profile_image_url to persons

Revision ID: c50eae065823
Revises: 708fdfa96128
Create Date: 2026-03-17 13:23:52.087052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50eae065823'
down_revision = '708fdfa96128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=1000), nullable=True))
        batch_op.create_index('ix_persons_tenant_email', ['tenant_id', 'email'], unique=False)
        batch_op.create_index('ix_persons_tenant_linkedin_url', ['tenant_id', 'linkedin_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index('ix_persons_tenant_linkedin_url')
        batch_op.drop_index('ix_persons_tenant_email')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('company')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
