"""add saved_paths and activities tables

Revision ID: e8279d3cd8ac
Revises: 430eb7832091
Create Date: 2026-03-17 21:05:36.412773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8279d3cd8ac'
down_revision = '430eb7832091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_activities_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_activities_user_id', ['user_id'], unique=False)

    op.create_table('saved_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_person_id', sa.Integer(), nullable=False),
    sa.Column('to_person_id', sa.Integer(), nullable=False),
    sa.Column('path_ids', sa.Text(), nullable=False),
    sa.Column('degrees', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_paths', schema=None) as batch_op:
        batch_op.create_index('ix_saved_paths_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_saved_paths_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_paths', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_paths_user_id')
        batch_op.drop_index('ix_saved_paths_tenant_id')

    op.drop_table('saved_paths')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_user_id')
        batch_op.drop_index('ix_activities_tenant_id')
        batch_op.drop_index('ix_activities_created_at')

    op.drop_table('activities')
    # ### end Alembic commands ###
