import { useNavigate } from 'react-router-dom'

export default function Privacy() {
  const navigate = useNavigate()
  const updated  = 'March 21, 2026'

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-page)', color: 'var(--text-primary)' }}>
      <nav style={{ padding: '16px 32px', borderBottom: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' }} onClick={() => navigate('/')}>
          <div style={{ width: '28px', height: '28px', borderRadius: '7px', background: 'var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <svg width="14" height="14" viewBox="0 0 18 18" fill="none">
              <circle cx="9" cy="9" r="3" fill="white" />
              <circle cx="9" cy="9" r="7" stroke="white" strokeWidth="1.5" fill="none" />
              <circle cx="9" cy="2" r="1.5" fill="white" /><circle cx="9" cy="16" r="1.5" fill="white" />
              <circle cx="2" cy="9" r="1.5" fill="white" /><circle cx="16" cy="9" r="1.5" fill="white" />
            </svg>
          </div>
          <span style={{ fontFamily: 'Syne, sans-serif', fontWeight: 700, fontSize: '16px' }}>OrbitSix</span>
        </div>
      </nav>

      <div style={{ maxWidth: '720px', margin: '0 auto', padding: '56px 32px 80px' }}>
        <h1 style={{ fontFamily: 'Syne, sans-serif', fontSize: '32px', fontWeight: 700, marginBottom: '8px' }}>Privacy Policy</h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '14px', marginBottom: '40px' }}>Last updated: {updated}</p>

        {[
          {
            h: '1. Information We Collect',
            p: 'We collect information you provide directly: your name, email address, and password when you register; contact data you import (names, companies, LinkedIn URLs); target companies and outreach notes you create within the Service. We also collect usage data automatically: log files, IP addresses, browser type, pages visited, and feature usage to operate and improve the Service.',
          },
          {
            h: '2. Contact Data You Import',
            p: 'OrbitSix processes the professional contact data (names, job titles, companies, LinkedIn profile URLs) that you import via CSV upload or our browser extension. This data is stored on your behalf to power network path-finding and outreach features. We do not sell, share, or use your imported contact data to build profiles on third parties or for advertising.',
          },
          {
            h: '3. How We Use Your Information',
            p: 'We use collected information to: provide, maintain, and improve the Service; authenticate your account; generate AI-powered network insights and draft messages; send transactional emails (account verification, password reset, weekly digests); process payments via Stripe; respond to support requests; and detect and prevent fraud or abuse.',
          },
          {
            h: '4. Data Sharing',
            p: 'We do not sell your personal information. We share data only with: (a) service providers who process data on our behalf (Anthropic for AI, Stripe for billing, Resend for email, Railway for hosting) under confidentiality obligations; (b) law enforcement when required by law; (c) a successor entity in the event of a merger or acquisition, with notice to you.',
          },
          {
            h: '5. AI Processing',
            p: 'Messages and network data you submit to the AI agent feature are sent to Anthropic\'s API to generate responses. Anthropic\'s data use is governed by their API usage policies. We do not use your data to train AI models. Draft messages generated by AI are stored on our servers only if you save them to your outreach tracker.',
          },
          {
            h: '6. Data Retention',
            p: 'We retain your account data and imported contacts for as long as your account is active. If you delete your account, we will delete your personal data and imported contact data within 30 days, except where we are required to retain it for legal or compliance purposes.',
          },
          {
            h: '7. Security',
            p: 'We use industry-standard measures to protect your data: HTTPS encryption in transit, bcrypt-hashed passwords, JWT-based authentication with expiry, and access controls limiting data to the authenticated account. No method of transmission or storage is 100% secure; we cannot guarantee absolute security.',
          },
          {
            h: '8. Cookies and Local Storage',
            p: 'We use browser localStorage to store your authentication token and session preferences. We do not use third-party tracking cookies or advertising pixels. Our browser extension stores your API token and sync timestamps in chrome.storage.local, which is private to the extension.',
          },
          {
            h: '9. Your Rights',
            p: 'You may access, correct, or delete your personal data at any time through your account settings or by emailing hello@orbitsix.com. You may export your imported contact data or request its deletion. If you are in the EEA or UK, you have rights under GDPR including data portability, restriction of processing, and the right to lodge a complaint with a supervisory authority.',
          },
          {
            h: '10. Children',
            p: 'The Service is not directed to children under 18. We do not knowingly collect personal information from anyone under 18. If we learn we have collected such data, we will delete it promptly.',
          },
          {
            h: '11. Changes to This Policy',
            p: 'We may update this Privacy Policy from time to time. We will notify you of material changes by email or by posting a notice within the Service. Continued use after changes take effect constitutes acceptance of the updated policy.',
          },
          {
            h: '12. Contact',
            p: 'Questions about this Privacy Policy or our data practices? Email us at hello@orbitsix.com.',
          },
        ].map(({ h, p }) => (
          <div key={h} style={{ marginBottom: '28px' }}>
            <h2 style={{ fontFamily: 'Syne, sans-serif', fontSize: '17px', fontWeight: 700, margin: '0 0 8px', color: 'var(--text-primary)' }}>{h}</h2>
            <p style={{ fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>{p}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
